name: Generate requirements.txt

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pipenv' # Optional: Caches the pipenv environment
     

    - name: Install pipenv
      run: pip install pipenv

    - name: Install project dependencies and generate requirements.txt
      run: |
        pipenv install --dev --skip-lock # Install dependencies first to make sure they are in the venv
        pipenv requirements --dev > requirements.txt
     

    - name: Upload requirements.txt as artifact (optional)
      uses: actions/upload-artifact@v4
      with:
        name: requirements-file
        path: requirements.txt

    - name: Commit and push requirements.txt (optional, if you want to commit the file back to the repo)
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add requirements.txt
        git commit -m "Generate requirements.txt from Pipfile.lock"
        git push
      continue-on-error: true # Prevents workflow failure if no changes to commit
